version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5-node

    steps:
      - checkout

      - restore_cache:
          keys:
            - logs-bundle-v2-{{ checksum "logs_page_view.gemspec" }}

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: logs-bundle-v2-{{ checksum "logs_page_view.gemspec" }}
          paths:
            - vendor/bundle

      - run:
          name: Run Rspec
          command: bundle exec rspec
